CREATE EXTENSION IF NOT EXISTS vector;

CREATE TABLE IF NOT EXISTS docs_chunks (
    record_id varchar PRIMARY KEY,
    chunk_id varchar NOT NULL,
    doc_id varchar NOT NULL,
    chunk_index integer NOT NULL,
    source varchar NOT NULL,
    source_path varchar NOT NULL,
    url varchar,
    title varchar NOT NULL,
    headings json NOT NULL,
    kind varchar NOT NULL,
    text text NOT NULL,
    content text NOT NULL,
    char_count integer NOT NULL,
    estimated_tokens integer NOT NULL,
    content_hash varchar NOT NULL,
    reference_symbols json NOT NULL,
    embedding halfvec(3072) NOT NULL,
    embedding_model varchar NOT NULL,
    embedding_dimensions integer NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS docs_chunks_chunk_id_idx ON docs_chunks (chunk_id);
CREATE INDEX IF NOT EXISTS docs_chunks_doc_id_idx ON docs_chunks (doc_id);
CREATE INDEX IF NOT EXISTS docs_chunks_kind_idx ON docs_chunks (kind);
CREATE INDEX IF NOT EXISTS docs_chunks_embedding_hnsw_idx
    ON docs_chunks
    USING hnsw (embedding halfvec_cosine_ops)
    WITH (m = 16, ef_construction = 64);

CREATE TABLE IF NOT EXISTS chat_messages (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversation_id varchar NOT NULL,
    role varchar NOT NULL,
    content text NOT NULL,
    created_at timestamptz NOT NULL,
    request_id varchar,
    message_index integer,
    provider varchar,
    model varchar,
    retrieved_document_ids json NOT NULL DEFAULT '[]'::json,
    message_metadata json NOT NULL DEFAULT '{}'::json
);

CREATE INDEX IF NOT EXISTS chat_messages_conversation_idx
    ON chat_messages (conversation_id, created_at);
CREATE INDEX IF NOT EXISTS chat_messages_request_idx
    ON chat_messages (request_id);
